# Generated by Django 3.1.7 on 2021-03-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='trade',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer'), ('Both', 'Both')], max_length=50, null=True),
        ),
    ]
