# Generated by Django 3.1.7 on 2021-03-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_person_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='genre',
        ),
        migrations.AddField(
            model_name='seller',
            name='adresse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
