# Generated by Django 3.1.7 on 2021-04-01 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210331_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='person_ptr',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
