# Generated by Django 3.1.7 on 2021-03-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbordClient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productt',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productt',
            name='category',
            field=models.CharField(choices=[('Accessoirs', 'Accessoirs'), ('Sacs', 'Sacs'), ('Chaussures', 'Chaussures'), ('Robes', 'Robes')], max_length=200, null=True),
        ),
    ]
